### ISSUE TITLE
Gerber Files not "processable" by Aisler.net

### ISSUE THREAD

**Issue by cardassian** [kees1948/UniFLEX#3]
In the Hardware directory, the different PCB are located as subdirectories.
Within the subdirectories a ".zip" file can be found with gerber files. Usually
you just upload these gerber files to your favourite PCB processing firm
and you just get the finished PCBs approx. two weeks later. Being a local firm in
Europe and moreover CO2 aware, I use "aisler.net" as my PCB producer (yes, 
it costs a few bugs more than far-east manufactures, so what?).

I get an error message upon uploading, reading that there are "no gerber files"
in the ZIP archive. I tried renaming/upper/lower case tricks within the archive names,
nothing helped. (Being a gerber illiterate, I did not touch gerber file contents).

Any ideas?

**Comment by kees1948** [comment]
Hello, for as long as the project runs 2019+ I have sent the .zip to various board foundries and I never ran into difficulty for them to process these files. With gerbv and gerbview one can open the layers and view them.

It is entirely possible that the "naming" of the files is a problem, especially the suffix. But that can be renamed if the production facility needs that. The 'better' companies have smart parsers where from the filename they determine the layer of the board.

**Comment by kees1948** [comment]
Hello,

If you want a really nice example of a good PCB foundry, take a peek at  https://be.eurocircuits.com/
You can upload your zip file, have it analyzed and VISUALIZED even
