### ISSUE TITLE
CPU09MON schematics does not match the Gerber files in 09MON_210622.ZIP

### ISSUE THREAD

**Issue by cardassian** [kees1948/UniFLEX#4]
CPU09 (RAM (1MB), ROM (2K), timer, console port) is in the list of the "minimal system". The corresponding
Gerber file in the directory is "09MON_210622.ZIP". Looking at the Gerber files with gerbv (Linux) it seems to me
that these gerber files do not match the target schematics.

**Comment by kees1948** [comment]
I found that you were absolutely right. The design present was for a special ACIA board for the CPU09GPP

I have placed the right one now on GitHub

Thanks for pointing it out
